title: SEO Analytics
url: "https://seoanalytics.com.br"
baseurl:
google_analytics_key: UA-103037512-1
google_maps_javascript_api_key:
disqus_shortname: seoanalytics-2

# Default description in social shares for the jekyll-seo-tag gem
description: Encontre os melhores consultores de SEO, Data Analytics e Marketing de Performance. Nós te ajudamos a encontrar um consultor data-driven para trazer os melhores resultados de conversão com o melhor custo benefício para seu negócio.

# Author details for the jekyll-seo-tag gem
# Author settings
author: Fabiola Faria # add your name
author-pic: fabiola-foto.jpg
about-author: Mais de 8 anos de experiência com SEO e Data Analytics. Em sua experiência já obteve crescimento de +500% no tráfego mensal orgânico, e contribuindo com estratégias que colocaram o site em 1ª posição nos principais termos de busca.
 
name:
email:
twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Urban Template
  links:
    - https://github.com/CloudCannon/urban-jekyll-template

timezone: Etc/UTC

collections:
  staff_members:
    output: true
  consultoria:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "consultoria"
    values:
      layout: "consultoria"
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      layout: 
      _options:
        image_path:
          width: 2000
          height: 2000
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
