disqus-identifier: seoanalytics-2

# Permalinks
permalink:        pretty

collections:
  projects:
    output: true
  links:
    output: true
  music:
    output: true
  stories:
    output: true        
    
    
# Banner Section
hero: 112.jpg
hero-title: 
hero-description: 

# Social Media Links (Links are located in hero and footer)
twitter: 
facebook: 
google-plus:
instagram: 
pinterest: 
youtube: 

# Author - Creator
author-name: Ben Campbell
author-image: 10.jpg
about-author: My name is Ben Campbell. I'm an actor and a musician. Retro wolf banjo succulen tsgoch ujang tumeric hammock offal.
author-email: help.example@gmail.com
author-twitter: https://twitter.com/
author-facebook: https://twitter.com/
author-instagram: https://www.instagram.com/
author-pinterest: https://pinterest.com/

# Other Authors - here you can add Other authors. For example Natali_Braxton
authors:
  Natali_Braxton:
    author-name: Natali Braxton
    author-image: 111.jpg
    about-author: My name is Natali Braxton. I love walking, I play the guitar in my spare time. And also write articles about different technologies.
    author-email: natali.example@gmail.com
    author-twitter: https://twitter.com/
    author-facebook: https://twitter.com/
    author-instagram: https://www.instagram.com/
    author-pinterest: https://pinterest.com/