# Permalinks
permalink:        pretty

collections:
  projects:
    output: true
  links:
    output: true
  music:
    output: true
  stories:
    output: true        
    
    
# Banner Section
hero: 112.jpg
hero-title: 
hero-description: 

# Social Media Links (Links are located in hero and footer)
twitter: 
facebook: 
google-plus:
instagram: 
pinterest: 
youtube: 