# Permalinks
permalink:        pretty

collections:
  projects:
    output: true
  links:
    output: true
  music:
    output: true
  stories:
    output: true        
    
    
# Banner Section
hero: 112.jpg
hero-title: SEOAnalytics
hero-description: 